apiVersion: v1
kind: ConfigMap
metadata:
  name: technova-config
  labels:
    app: technova
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGO_URI: "mongodb://mongodb-service:27017/technova"
  VITE_API_URL: "" # Relies on Nginx proxy rules to resolve API paths relative to base URL
