apiVersion: v1
kind: Secret
metadata:
  name: technova-secret
  labels:
    app: technova
type: Opaque
data:
  # Base64 encoded representation of: supersecretjwtkey12345
  JWT_SECRET: c3VwZXJzZWNyZXRqd3RrZXkxMjM0NQ==
